openapi: 3.1.0
info:
  title: SMS OpenApi
  description: |
    Some existing API Server for sending POST message to help 
    with authentication at [https://bayamsell.com](https://pay.bayamsell.com)
  termsOfService: https://blog.ssegning.com
  contact:
    email: dev@ssegning.com
  license:
    name: MIT
    identifier: MIT
  version: 26.5.2
externalDocs:
  description: Find out more about calling setting up an external service to verify phone number
  url: https://ssegning.com
servers:
  - url: http://prism:4010
    description: Mock server
  - url: http://localhost:8080
    description: Dev server
  - url: https://sms-api-server:port
    description: Production server
tags:
  - name: sms
    description: All about sending an SMS
paths:
  /sms/send:
    post:
      tags:
        - sms
      summary: Send sms
      description: Send an SMS to the phone number provided
      operationId: sendSms
      security:
        - basic_auth: []
        - oauth2: []
      requestBody:
        description: Send sms request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendSmsRequest'
        required: true
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendSmsResponse"
        401:
          description: "Unauthorized - Invalid or missing authentication"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "unauthorized"
                    
  /sms/validate:
    post:
      tags:
        - sms
      summary: Validate sms
      description: Send an SMS to the phone number provided
      operationId: validateSms
      security:
        - basic_auth: []
        - oauth2: []
      requestBody:
        description: Validate sms request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmTanRequest'
        required: true
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmTanResponse"
        401:
          description: "Unauthorized - Invalid or missing authentication"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "unauthorized"

components:
  schemas:
    Metadata:
      type: object
      description: Optional, extra context passed by the Keycloak plugin.
      additionalProperties: true
    ConfirmTanRequest:
      type: object
      properties:
        hash:
          type: string
        code:
          type: string
        phoneNumber:
          type: string
        realm:
          type: string
        clientId:
          type: string
        ipAddress:
          type: string
        userAgent:
          type: string
        sessionId:
          type: string
        traceId:
          type: string
        metadata:
          $ref: '#/components/schemas/Metadata'
      required:
        - phoneNumber
        - hash
        - code
    ConfirmTanResponse:
      type: object
      properties:
        valid:
          type: boolean
      required:
        - valid
    SendSmsRequest:
      type: object
      properties:
        phoneNumber:
          type: string
        realm:
          type: string
        clientId:
          type: string
        ipAddress:
          type: string
        userAgent:
          type: string
        sessionId:
          type: string
        traceId:
          type: string
        metadata:
          $ref: '#/components/schemas/Metadata'
      required:
        - phoneNumber
    SmsStatus:
      type: string
      enum:
        - SENT
        - ERROR
        - PENDING
    SendSmsResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/SmsStatus'
        description:
          type: string
          maxLength: 200
        hash:
          type: string
      required:
        - status
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'http://token-mock:8080/token'
          scopes: {}
