openapi: 3.0.3
info:
  title: SMS OpenApi
  description: |
    Some existing API Server for sending POST message to help 
    with authentication at [https://bayamsell.com](https://pay.bayamsell.com)
  termsOfService: https://blog.ssegning.com
  contact:
    email: dev@ssegning.com
  license:
    name: MIT
  version: 26.1.3
externalDocs:
  description: Find out more about calling setting up an external service to verify phone number
  url: https://ssegning.com
servers:
  - url: http://localhost:8080
    description: Dev server
  - url: https://sms-api-server:port
    description: Production server
tags:
  - name: sms
    description: All about sending an SMS
paths:
  /sms/send:
    post:
      tags:
        - sms
      summary: Send sms
      description: Send an SMS to the phone number provided
      operationId: sendSms
      security:
        - oauth2: []
      requestBody:
        description: Send sms request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendSmsRequest'
        required: true
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendSmsResponse"
  /sms/validate:
    post:
      tags:
        - sms
      summary: Validate sms
      description: Send an SMS to the phone number provided
      operationId: validateSms
      security:
        - oauth2: []
      requestBody:
        description: Validate sms request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmTanRequest'
        required: true
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfirmTanResponse"

  /token:  # New endpoint for OAuth2 token issuance
    post:
      tags:
        - sms
      summary: Get OAuth2 access token
      description: Issues an access token using the Client Credentials Grant
      operationId: getToken
      requestBody:
        description: Token request
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  example: "client_credentials"
                client_id:
                  type: string
                  example: "some-client-id"
                client_secret:
                  type: string
                  example: "some-client-secret"
              required:
                - grant_type
                - client_id
                - client_secret
      responses:
        200:
          description: "Token issued successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: "mock-access-token"
                  token_type:
                    type: string
                    example: "Bearer"
                  expires_in:
                    type: integer
                    example: 3600
        401:
          description: "Invalid client credentials"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "invalid_client"
components:
  schemas:
    ConfirmTanRequest:
      type: object
      properties:
        hash:
          type: string
        code:
          type: string
        phoneNumber:
          type: string
      required:
        - phoneNumber
        - hash
        - code
    ConfirmTanResponse:
      type: object
      properties:
        valid:
          type: boolean
      required:
        - valid
    SendSmsRequest:
      type: object
      properties:
        phoneNumber:
          type: string
      required:
        - phoneNumber
    SmsStatus:
      type: string
      enum:
        - SENT
        - ERROR
        - PENDING
    SendSmsResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/SmsStatus'
        description:
          type: string
          maxLength: 200
        hash:
          type: string
      required:
        - status
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /token
          scopes: {}
